package pojo;
// Generated Sep 19, 2024 11:28:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posts generated by hbm2java
 */
public class Posts implements java.io.Serializable {

     private Integer id;
     private Users users;
     private String title;
     private String content;
     private Date createdAt;
     private Set<Tags> tagses = new HashSet<>(0);
     private Set commentses = new HashSet(0);

    public Posts() {
    }

	
    public Posts(Users users, String title, String content, Date createdAt) {
        this.users = users;
        this.title = title;
        this.content = content;
        this.createdAt = createdAt;
    }
    
    public Posts(Users users, String title, String content, Date createdAt, Set tagses, Set commentses) {
       this.users = users;
       this.title = title;
       this.content = content;
       this.createdAt = createdAt;
       this.tagses = tagses;
       this.commentses = commentses;
    }
    
    public Posts(int id, Users users, String title, String content, Date createdAt, Set tagses, Set commentses) {
       this.id = id;
       this.users = users;
       this.title = title;
       this.content = content;
       this.createdAt = createdAt;
       this.tagses = tagses;
       this.commentses = commentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    public Set<Tags> getTagses() {
        return this.tagses;
    }
    
    public void setTagses(Set<Tags> tagses) {
        this.tagses = tagses;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
}


