package pojo;
// Generated Sep 19, 2024 11:28:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set postses = new HashSet(0);

    public Tags() {
    }

	
    public Tags(String name) {
        this.name = name;
    }
    
    public Tags(String name, String description, Set postses) {
       this.name = name;
       this.description = description;
       this.postses = postses;
    }
    
    public Tags(int id, String name, String description, Set postses) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.postses = postses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }




}


