package pojo;
// Generated Sep 19, 2024 11:28:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

     private Integer id;
     
     @NotNull(message = "Username is required")
     @NotBlank(message = "Username is required")
     @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
     private String username;
     
     @NotNull(message = "Email is required")
     @Email(message = "Email should be valid")
     @Size(max = 100, message = "Email must not exceed 100 characters")
     private String email;
     
     @NotNull(message = "Password is required")
     @NotBlank(message = "Password is required")
     @Size(min = 8, message = "Password must be at least 8 characters long")
     private String password;
     
     private Date createdAt;
     private Set commentses = new HashSet(0);
     private Set postses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String email, String password, Date createdAt) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.createdAt = createdAt;
    }
    
    public Users(String username, String email, String password, Date createdAt, Set commentses, Set postses) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.createdAt = createdAt;
       this.commentses = commentses;
       this.postses = postses;
    }
    
    public Users(int id, String username, String email, String password, Date createdAt, Set commentses, Set postses) {
       this.id = id;
       this.username = username;
       this.email = email;
       this.password = password;
       this.createdAt = createdAt;
       this.commentses = commentses;
       this.postses = postses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }




}


